In [ ]:
Numpy - Numerical Python 

In [2]:
import numpy as np 

In [ ]:
Use Cases of numpy: 
1] Statistics: min,max,mean,mode,median
2] Matrices 3] Linear Algebra 4] Logarithmic 5] Trigonometry

In [ ]:
Properties of Numpy array:
1] Numpy is a collection of homogenous data types. (same data type)
2] Numpy array is faster than list 
3] Numpy array is mutable (changeable)
4] Multi dimensional support - 0D,1D,2D,...nD
5] Numpy array takes less memory than list
6] Numpy array is also used in Computer vision(image processing)

In [ ]:
Numpy Functions: 

In [ ]:
1] np.array(list/tuple/dict/Series)
a] Array can be created using list,tuple,dict or Series
b] Note: Using set is not recommended, as we might lose our data as it doesnt allow duplicates

In [ ]:
lst = [1,2,3,4] # int 
arr1= np.array(lst)
arr1

array([1, 2, 3, 4])

In [ ]:
Data Type Hierarchy - int,float,complex,str

In [ ]:
lst = [1,2,3,4,5.4] # int,float - float
arr1= np.array(lst)
arr1

array([1. , 2. , 3. , 4. , 5.4])

In [ ]:
lst = [1,2,3,4,5.4,1+2j] # int,float,complex - complex
arr1= np.array(lst)
arr1

array([1. +0.j, 2. +0.j, 3. +0.j, 4. +0.j, 5.4+0.j, 1. +2.j])

In [ ]:
lst = [1,2,3,4,5.4,1+2j,"a"] #int,float,complex,str - str
arr1= np.array(lst)
arr1

array(['1', '2', '3', '4', '5.4', '(1+2j)', 'a'], dtype='<U64')

In [8]:
float_list = [1.2,1.3,1.4,1.5] # float 
arr1 = np.array(float_list)
arr1

array([1.2, 1.3, 1.4, 1.5])

In [9]:
print(arr1)

[1.2 1.3 1.4 1.5]


In [ ]:
Type Casting in Numpy array

In [ ]:
int - float,complex,str 
float - int,complex,str
complex - int,float not possible, str

In [11]:
float_list = [1.2,2.3,3.4,4.5]
arr=np.array(float_list,dtype="int") 
print(arr)

[1 2 3 4]


In [17]:
float_list = [1,2,3,4]
int_arr=np.array(float_list,dtype="float") 
print(int_arr)

[1. 2. 3. 4.]


In [14]:
lst/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [18]:
int_arr/2

array([0.5, 1. , 1.5, 2. ])

In [19]:
int_arr*2

array([2., 4., 6., 8.])

In [20]:
int_arr**2

array([ 1.,  4.,  9., 16.])

In [ ]:
Numpy array works faster than for loop

In [ ]:
import time 
start_time = time.time()
lst = [i**2 for i in range(1,100)] # list and for 
total_time = time.time() - start_time
print(total_time)

7.867813110351562e-05


In [22]:
start_time=time.time()
array = np.array(range(1,100))
array=array**2
total_time = time.time() - start_time
print(total_time)

0.0002257823944091797


In [ ]:
Time taken by np array < Time taken by for loop

In [ ]:
2] array.ndim = To know the dimension of an array - It is an array function

In [37]:
# A] 0-D array
array0 = np.array(1)
print(array0.ndim)
print(array0.shape)

0
()


In [44]:
# B] 1D array - It is collection of multiple OD arrays(list)
array1 = np.array([1,2,3,4])
print(array1.ndim)
print(array1.shape) # columns
print(array1.size) 


1
(4,)
4


In [46]:
# C] 2D array - It is collection of multiple 1D arrays(nested list)
array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(array2.ndim)
print(array2.shape) #rows,columns
print(array2.size) 

2
(2, 4)
8


In [47]:
# D] 3D array - It is collection of multiple 2D arrays
array3 = np.array([[[1,2,3,4],[5,6,7,8]],
                   [[9,10,11,12],[13,14,15,16]]])
print(array3.ndim)
print(array3.shape)
print(array3.size)

3
(2, 2, 4)
16


In [ ]:
array = np.array([[[1,2,3]]])
print(array.ndim)
print(array.shape)

3
(1, 1, 3)


In [ ]:
3] array.shape -  Output Datatype is tuple

In [ ]:
array.ndmin parameter - lower to higher dimensions

In [ ]:
Note: Reducing higher dimensions to lower dimensions is not possible directly by ndmin parameter

In [49]:
arr1 = np.array([[3,4],[4,5]],ndmin=1)
arr1.ndim

2

In [50]:
arr1 = np.array([[3,4],[4,5]],ndmin=3)
arr1.ndim

3

In [51]:
print(arr1)

[[[3 4]
  [4 5]]]


In [ ]:
5] array.reshape(new_shape)

In [57]:
array1 = np.array([1,2,3,4]) # (4) - (4,1),(1,4),(2,2)
print(array1.reshape(4,1))
print("************************")
print(array1.reshape(1,4))
print("************************")
print(array1.reshape(2,2))


[[1]
 [2]
 [3]
 [4]]
************************
[[1 2 3 4]]
************************
[[1 2]
 [3 4]]


In [ ]:
# Indexing in numpy: 1D array
arr1 = np.array([1,2,3,4,5])
arr1[0],arr1[-1],arr1[2],arr1[-3]

(np.int64(1), np.int64(5), np.int64(3), np.int64(3))

In [64]:
# Indexing in 2D array
array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(array2)
array2[0][1],array2[0,1],array2[1,2],array2[1][2]


[[1 2 3 4]
 [5 6 7 8]]


(np.int64(2), np.int64(2), np.int64(7), np.int64(7))

In [ ]:
# Indexing in 3D array
array3 = np.array([[[1,2,3,4],[5,6,7,8]],
                   [[9,10,11,12],[13,14,15,16]]])
print(array3)
array3[0][1][1],array3[0,1,1],array3[1,1,3],array3[1,1,-1]


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


(np.int64(6), np.int64(6), np.int64(16), np.int64(16))

In [ ]:
# Slicing in numpy: 
[start_index:end_index(exclude):step_size(default=1)]

In [ ]:
# Slicing in 1D array 
arr1 = np.array([1,2,3,4,5,6])
print(arr1[1:4],arr1[-5:-2],arr1[-5:4],arr1[1:-2])
print(arr1[::2])
print(arr1[1::2])
print(arr1[-2::-2])
print(arr1[::-2])

[2 3 4] [2 3 4] [2 3 4] [2 3 4]
[1 3 5]
[2 4 6]
[5 3 1]
[6 4 2]


In [85]:
# Slicing in 2D array
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [90]:
print(array2[0,1:3])
print(array2[:,1:3])
print(array2[::2,1::2])
print(array2[1:,1::2])

[2 3]
[[ 2  3]
 [ 6  7]
 [10 11]]
[[ 2  4]
 [10 12]]
[[ 6  8]
 [10 12]]


In [96]:
# Slicing in 3D array
array3 = np.array([[[1,2,3,4],[5,6,7,8],[1,2,3,4]],
                   [[9,10,11,12],[13,14,15,16],[1,2,3,4]],
                   [[17,18,19,20],[21,22,23,24],[1,2,3,4]]])
array3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [ 1,  2,  3,  4]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24],
        [ 1,  2,  3,  4]]])

In [97]:
# 1st plane and 3rd plane, - 1st 2 
print(array3[::2,:,:2])
# [5 6]
#   [13 14]
#   [21 22]
print(array3[:,1,:2])

[[[ 1  2]
  [ 5  6]
  [ 1  2]]

 [[17 18]
  [21 22]
  [ 1  2]]]
[[ 5  6]
 [13 14]
 [21 22]]


In [98]:
# Acces Numpy items using for loop 
arr1 = np.array([1,2,3])
for i in arr1: print(i,end=" ")

1 2 3 

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]]) # In case of 2D array, it prints index wise not element wise 
for i in arr2: print(i)

[1 2 3]
[4 5 6]


In [101]:
arr2 = np.array([[1,2,3],[4,5,6]]) # In case of 2D array, it prints index wise not element wise 
for i in arr2: 
    for j in i:
        print(j,end=" ")

1 2 3 4 5 6 

In [ ]:
np.nditer(array)
np.ndenumerate(array)

In [102]:
for i in np.nditer(arr1):
    print(i,end=" ")

1 2 3 

In [104]:
for index,value in np.ndenumerate(arr1):
    print(index,value)

(0,) 1
(1,) 2
(2,) 3


In [105]:
for i in np.nditer(arr2):
    print(i,end=" ")

1 2 3 4 5 6 

In [107]:
for index,value in np.ndenumerate(arr2):
    print(index,value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [115]:
array = arr1.tolist()
array2 = arr2.tolist()
print(f"{array},\n{array2}")
print(f"{arr2.flatten()}")
print(f"{arr2.flatten().tolist()}")

[1, 2, 3],
[[1, 2, 3], [4, 5, 6]]
[1 2 3 4 5 6]
[1, 2, 3, 4, 5, 6]


In [ ]:
Important functions: 
1] array.copy() 
2] np.zeros(shape) 
3] np.ones(shape)
4] np.full(shape,value)
5] np.append(arr1,arr2,axis=)
6] np.concatenate([arr1,arr2,arr3,..,arrN],axis=)
7] np.arange(low,high,step_size)
8] np.random()
  8.1] np.random().rand()
  8.2] np.random().randint()
  8.3] np.random().ranf()
  8.4] np.random().randn()
  8.5] np.random().uniform()
  8.6] np.random().sample()

In [ ]:
# 1] array.copy()
array1 = np.array([1,2,3])
array2 = array1
array2[1]=4
print(array1)
print(array2)
# To avoid this we use array.copy()

[1 4 3]
[1 4 3]


In [122]:
array1 = np.array([1,2,3])
array2 = array1.copy()
array2[1]=4
print(array1)
print(array2)

[1 2 3]
[1 4 3]


In [ ]:
# 2] np.zeros(shape,dtype) - Returns an array of 0 for mentioned shape 
# 3] np.ones(shape,dtype) - Returns an array of 1 for mentioned shape 
# 4] np.full(shape,value,dtype) - Returns an array of value for mentioned shape 

In [ ]:
a0 = np.zeros((2,3),int) # By default - float 
a0

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
a1 = np.ones((2,3),int)# By default - float 
a1


array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
a2 = np.full((2,3),2)# By default - int 
a2


array([[2, 2, 2],
       [2, 2, 2]])

In [146]:
import pandas as pd 

In [159]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
target = np.append(arr1,arr2,axis=0)
print(target)
pd.DataFrame(target)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


0  1  2  3
0  1  2  3  4
1  5  6  7  8
2  1  2  3  4
3  5  6  7  8

In [160]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
target = np.append(arr1,arr2,axis=1)
print(target)
pd.DataFrame(target)

[[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


0  1  2  3  4  5  6  7
0  1  2  3  4  1  2  3  4
1  5  6  7  8  5  6  7  8

In [165]:
#np.concatenate - Join 2 or multiple arrays
arr0 = np.zeros(5,int)
arr1 = np.ones(5,int)
arr2 = np.full(5,2)
print(arr0,arr1,arr2)
target = np.concatenate([arr0,arr1,arr2])
target
#pd.DataFrame(target)

[0 0 0 0 0] [1 1 1 1 1] [2 2 2 2 2]


array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

In [170]:
arr1 = np.random.randint(0,10,(2,4))
arr2 = np.random.randint(10,20,(2,4))
arr3 = np.random.randint(20,30,(2,4))
target = np.concatenate([arr1,arr2,arr3],axis=0)
target

array([[ 1,  4,  3,  0],
       [ 3,  9,  1,  4],
       [19, 18, 15, 16],
       [18, 11, 10, 19],
       [24, 24, 24, 25],
       [23, 21, 29, 28]], dtype=int32)

In [171]:
target = np.concatenate([arr1,arr2,arr3],axis=1)
target

array([[ 1,  4,  3,  0, 19, 18, 15, 16, 24, 24, 24, 25],
       [ 3,  9,  1,  4, 18, 11, 10, 19, 23, 21, 29, 28]], dtype=int32)

In [172]:
for i in np.arange(0,10,2):
    print(i,end=" ")

0 2 4 6 8 

In [192]:
for i in np.arange(0,1,0.1):
    print(np.around(i,1),end=" ")

0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 

In [ ]:
range vs arange 
1] range returns a range object, while arange function returns a numpy array 
2] range is a built-in function in python while arange in numpy function 
3] range function can generate only integer values while arange function can be used to generate floating point arrays as well
 as integer values 
4] arange performs faster than range 
5] arange takes less memory space than range

In [ ]:
np.random.rand(size=) - It generates random floating values between 0 and 1 
np.random.ranf(size=) - It generates random floating values between 0 and 1 
np.random.sample(size=) - It generates random floating values between 0 and 1 
np.random.randint(low=,high=(exclude),size=) - It generates random integers within the specified range 
np.random.uniform(low=,high=(exclude),size=) - It generates random floating values within the specified range 
np.random.randn(shape) - It returns samples of normally distributed data

In [ ]:
float1 = np.random.rand(2,3) # No need to pass shape as tuple
float2 = np.random.ranf((2,3)) # Shape as tuple 
float3 = np.random.sample((2,3)) # Shape as tuple 
print(float1)
print(float2)
print(float3)

[[0.54491405 0.92563902 0.29538213]
 [0.38942477 0.45251368 0.44740819]]
[[0.0452094  0.53636698 0.77871143]
 [0.80604707 0.36158531 0.80776621]]
[[0.01018178 0.14187774 0.53793516]
 [0.62999476 0.1080919  0.19323805]]


In [189]:
np.random.randint(100000,999999,(2,2))

array([[250260, 514883],
       [682956, 395595]], dtype=int32)

In [193]:
np.random.uniform(100000,999999,(2,2))

array([[133263.26326443, 462646.25954163],
       [849546.65781721, 358453.78323663]])

In [198]:
np.random.randn(10)

array([-0.23942799,  0.71744208, -0.91123776, -0.41671588, -0.23922803,
       -0.17673163, -1.04747258,  0.3794564 ,  0.80770044,  1.37174393])

In [ ]:
Math functions: 
1] np.around(array,decimals=) - Rounds an array to the given number of decimals 
2] np.floor(array) - Returns the floor of the input,element-wise
3] np.ceil(array) - Returns the ceiling of the input,element-wise
4] np.add(array1,array2) - Add arguments element-wise
5] np.multiply(array1,array2) - Multiply arguments element-wise 
6] np.dot(array1,array2) - Dot product of 2 matrices(Scalar product)
7] np.sqrt(array1) - Returns the non-negative square root of an array, element-wise
8] np.cbrt(array2) - Returns the cube root of an array,element-wise 

In [ ]:
print("Round:",np.around(np.array((1.35,2.367,3.28282,4.2828282,5.29292)),2))
print("Floor:",np.floor(np.array((1.35,2.367,3.28282,4.2828282,5.29292)))) 
print("Ceil:",np.ceil(np.array((1.35,2.367,3.28282,4.2828282,5.29292))))

Round: [1.35 2.37 3.28 4.28 5.29]
Floor: [1. 2. 3. 4. 5.]
Ceil: [2. 3. 4. 5. 6.]


In [206]:
print(np.add(np.array((1,2)),np.array((2,3,5))))

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [205]:
print(np.add(np.array(3),np.array(4)))
print(np.add(np.array((1,2)),np.array(4)))
print(np.add(np.array((1,2)),np.array((2,3))))

7
[5 6]
[3 5]


In [207]:
print(np.multiply(np.array(3),np.array(4)))
print(np.multiply(np.array((1,2)),np.array(4)))
print(np.multiply(np.array((1,2)),np.array((2,3))))

12
[4 8]
[2 6]


In [ ]:
np.dot() # (1st columns = 2nd rows) ixj jxk = ixk
[a b f  [a
 d e g]  b
2 x 3    c]
         3 x 1 = [a*a + b*b +f*c
                  d*a + e*b +g*c] 2x1

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]]) 2x3
arr2 = np.array(([[3],[6],[7]])) 3x1
np.dot(arr1,arr2) #2x1 3+12+21=36,12+30+42=84

array([[36],
       [84]])

In [210]:
np.sqrt(np.array((4,9,16,25,36,49,64,81,100,121,144,169,70)))

array([ 2.        ,  3.        ,  4.        ,  5.        ,  6.        ,
        7.        ,  8.        ,  9.        , 10.        , 11.        ,
       12.        , 13.        ,  8.36660027])

In [212]:
np.cbrt(np.array((4,9,16,25,36,49,64,81,100,121,144,169,70)))

array([1.58740105, 2.08008382, 2.5198421 , 2.92401774, 3.30192725,
       3.65930571, 4.        , 4.32674871, 4.64158883, 4.94608744,
       5.24148279, 5.52877481, 4.1212853 ])

In [215]:
np.abs(np.array((-2,11,-3.5,4.2,-30)))

array([ 2. , 11. ,  3.5,  4.2, 30. ])

In [ ]:
Statistical Functions

In [ ]:
1] np.max(array,axis=) - Returns the maximum of an array or maximum along axis 
2] np.min(array,axis=) - Returns the minimum of an array or minimum along axis 
3] np.sum(array,axis=) - Compute the sum along the specified axis
4] np.mean(array,axis=) - Compute the arithmetic mean along the specified axis
5] np.median(array,axis=) - Compute the median along the specified axis
6] np.var(array,axis=) - Compute the variance along the specified axis
7] np.std(array,axis=) - Compute the standard deviation along the specified axis
8] np.percentile(array,q,axis=) - Compute the qth percentile along the specified axis
9] np.quantile(array,q,axis=) - Compute the qth quantile along the specified axis
10] np.nanmax(array,axis=)
11] np.nanmin(array,axis=)
12] np.nansum(array,axis=)
13] np.nanmean(array,axis=)
14] np.nanmedian(array,axis=)
15] np.nanvar(array,axis=)
16] np.nanstd(array,axis=)
17] np.nanpercentile(array,axis=)
18] np.nanquantile(array,axis=)

In [220]:
print("Maximum of an array: ",np.max(np.array([30,12,60,1,45,90,112])))
print("Minimum of an array: ",np.min(np.array([30,12,60,1,45,90,112])))
print("Sum of an array: ",np.sum(np.array([30,12,60,1,45,90,112])))
print("Mean of an array: ",np.mean(np.array([30,12,60,1,45,90,112])))
print("Median of an array: ",np.median(np.array([30,12,60,1,45,90,112]))) #- Even - (n/2th + n/2th+1)/2
print("Variance of an array: ",np.var(np.array([30,12,60,1,45,90,112]))) 
# Var = sum(Xi - Xmean)**2/N 
# std = sqrt(var)
print("Standard deviation of an array: ",np.std(np.array([30,12,60,1,45,90,112]))) 
print("Percentile of an array: ",np.percentile(np.array([30,12,60,1,45,90,112]),25))
print("Quantile of an array: ",np.quantile(np.array([30,12,60,1,45,90,112]),0.25)) 


Maximum of an array:  112
Minimum of an array:  1
Sum of an array:  350
Mean of an array:  50.0
Median of an array:  45.0
Variance of an array:  1402.0
Standard deviation of an array:  37.44329045369811
Percentile of an array:  21.0
Quantile of an array:  21.0


In [ ]:
np.nan - To introduce missing values 

In [ ]:
print("Maximum of an array: ",np.max(np.array([30,12,60,1,45,90,112,np.nan])))
print("Minimum of an array: ",np.min(np.array([30,12,60,1,45,90,112,np.nan])))
print("Sum of an array: ",np.sum(np.array([30,12,60,1,45,90,112,np.nan])))
print("Mean of an array: ",np.mean(np.array([30,12,60,1,45,90,112,np.nan])))
print("Median of an array: ",np.median(np.array([30,12,60,1,45,90,112,np.nan]))) #- Even - (n/2th + n/2th+1)/2
print("Variance of an array: ",np.var(np.array([30,12,60,1,45,90,112,np.nan]))) 
# Var = sum(Xi - Xmean)**2/N 
# std = sqrt(var)
print("Standard deviation of an array: ",np.std(np.array([30,12,60,1,45,90,112,np.nan]))) 
print("Percentile of an array: ",np.percentile(np.array([30,12,60,1,45,90,112,np.nan]),25))
print("Quantile of an array: ",np.quantile(np.array([30,12,60,1,45,90,112,np.nan]),0.25)) 


Maximum of an array:  nan
Minimum of an array:  nan
Sum of an array:  nan
Mean of an array:  nan
Median of an array:  nan
Variance of an array:  nan
Standard deviation of an array:  nan
Percentile of an array:  nan
Quantile of an array:  nan


In [223]:
print("Maximum of an array: ",np.nanmax(np.array([30,12,60,1,45,90,112,np.nan])))
print("Minimum of an array: ",np.nanmin(np.array([30,12,60,1,45,90,112,np.nan])))
print("Sum of an array: ",np.nansum(np.array([30,12,60,1,45,90,112,np.nan])))
print("Mean of an array: ",np.nanmean(np.array([30,12,60,1,45,90,112,np.nan])))
print("Median of an array: ",np.nanmedian(np.array([30,12,60,1,45,90,112,np.nan]))) #- Even - (n/2th + n/2th+1)/2
print("Variance of an array: ",np.nanvar(np.array([30,12,60,1,45,90,112,np.nan]))) 
# Var = sum(Xi - Xmean)**2/N 
# std = sqrt(var)
print("Standard deviation of an array: ",np.nanstd(np.array([30,12,60,1,45,90,112,np.nan]))) 
print("Percentile of an array: ",np.nanpercentile(np.array([30,12,60,1,45,90,112,np.nan]),25))
print("Quantile of an array: ",np.nanquantile(np.array([30,12,60,1,45,90,112,np.nan]),0.25)) 


Maximum of an array:  112.0
Minimum of an array:  1.0
Sum of an array:  350.0
Mean of an array:  50.0
Median of an array:  45.0
Variance of an array:  1402.0
Standard deviation of an array:  37.44329045369811
Percentile of an array:  21.0
Quantile of an array:  21.0


In [228]:
from scipy.stats import mode as m # Most frequenct occuring element 
m(np.array([3,2,1,2,1,2,1,2,1,2,3,3,3,3,1,1]))

ModeResult(mode=np.int64(1), count=np.int64(6))

In [ ]:
Linear Algebra Functions 

In [ ]:
1] np.linalg.solve(arrA,arrB)
- Used to solve linear equations of n variables 
If n is 2 - 2 equations 
If n is 3 - 3 equations 
Number of variables = Number of equations 
2x + 3y = 10
5x + 8y = 30 
arrA - coefficients
arrB - constant 

In [229]:
arrA = np.array([[2,3],[5,8]])
arrB = np.array([10,30])
np.linalg.solve(arrA,arrB)

array([-10.,  10.])

In [ ]:
# 2] Determinant of a matrix
a b 
c d - ad - bc

In [230]:
np.linalg.det(arrA)

np.float64(1.0000000000000009)

In [ ]:
# 3] Transpose of a matrix 
a b - a c
c d   b d

In [ ]:
np.linalg.matrix_transpose(arrA)

array([[2, 5],
       [3, 8]])

In [ ]:
# 4 Inverse of a matrix: 
A**-1 = adj(A)/|A|
adj(A) = [d -b
         -c  a] 

In [232]:
np.linalg.inv(arrA)

array([[ 8., -3.],
       [-5.,  2.]])

In [235]:
# 5] Eigen values and eigen vectors 
eigen_values = np.linalg.eigvals(arrA)
eigen_values

array([0.10102051, 9.89897949])

In [237]:
eigen_values,eigen_vectors = np.linalg.eig(arrA)
eigen_vectors

array([[-0.84494897, -0.35505103],
       [ 0.53484692, -0.93484692]])

In [ ]:
# 6] Polynomial equations
Polynomial equation is a combination of variables and coefficients set equal to 0 
degree: power
Equation with degree 1: ax + b = 0
Equation with degree 2: ax**2 +bx + c = 0 
Equation  with degree 3: ax**3 + bx**2 + cx+d ==0

In [238]:
c,b,a = 6,27,3
eq = np.polynomial.Polynomial([c,b,a])
eq

Polynomial([ 6., 27.,  3.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

In [ ]:
eq.roots() - Real roots

array([-8.77200187, -0.22799813])

In [ ]:
Roots can be real or imaginary(complex)

In [ ]:
7] Identity Matrix - Square Matrix 

In [240]:
np.identity(3) # We always pass a single integer 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
8] np.eye- Diagonal elements will be 1 rest will be 0 

In [242]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [ ]:
Trigonometry Functions

In [ ]:
np.pi # pi=3.14..., pi is in radian
1pi = 180 degree
2pi = 360 degree 
pi/2 = 90 degree
pi/3 = 60 degree
pi/4 = 45 degree 
pi/6 = 30 degree

In [244]:
# Degree 2 radian 
print(np.deg2rad(30))
# Radian 2 degree
np.rad2deg(0.5235987755982988)

0.5235987755982988


np.float64(29.999999999999996)

In [ ]:
print(np.sin(np.pi/60))
print(np.cos(np.pi/60))
print(np.tan(np.pi/60))
cosec=1/sin 
sec=1/cos 
cot=1/tan

0.05233595624294383
0.9986295347545738
0.052407779283041196


In [ ]:
Set(Numpy functions)

In [ ]:
1] np.unique(array) - Find the unique elements of an array

In [248]:
np.unique(np.array([3,2,1,2,1,2,1,2,1,2,3,3,3,3,1,1]))

array([1, 2, 3])

In [253]:
arrayA = np.array([1,2,3,4,5,6])
arrayB = np.array([4,5,6,7,8,9])
print(f"Intersection: {np.intersect1d(arrayA,arrayB)}")
print(f"Difference of arrayA: {np.setdiff1d(arrayA,arrayB)}")
print(f"Difference of arrayB: {np.setdiff1d(arrayB,arrayA)}")
print(f"Symmetric Difference: {np.setxor1d(arrayA,arrayB)}")
print(f"Union: {np.union1d(arrayA,arrayB)}")

Intersection: [4 5 6]
Difference of arrayA: [1 2 3]
Difference of arrayB: [7 8 9]
Symmetric Difference: [1 2 3 7 8 9]
Union: [1 2 3 4 5 6 7 8 9]


In [ ]:
Other functions: 
np.put(array,indices,values) - Replace the array elements - Updates 

In [254]:
arrayA = np.array([1,2,3,4,5,6])
arrayA

array([1, 2, 3, 4, 5, 6])

In [255]:
np.put(arrayA,[1,-2],[200,300])
arrayA

array([  1, 200,   3,   4, 300,   6])

In [ ]:
# np.repeat(value,n) - Repeats the value n times in an array 
np.repeat(10,3) # can pass n as integer only - Can only create 1d array

array([10, 10, 10])

In [ ]:
Sort function:

In [261]:
arrayA = np.array([30,12,60,1,45,90,112])
np.sort(arrayA)

array([  1,  12,  30,  45,  60,  90, 112])

In [262]:
# Descending order 
-np.sort(-arrayA)

array([112,  90,  60,  45,  30,  12,   1])

In [ ]:
arrayA = np.array([30,12,60,1,45,90,112])
arrayA.sort()
arrayA

array([  1,  12,  30,  45,  60,  90, 112])

In [ ]:
Logarithmic Functions: 
To reduce the impact of outliers 

In [ ]:
1] np.log(array) - Natural log 
2] np.log2(array) - log to the base 2 
2] np.log10(array) - log to the base 10

In [286]:
arrayA = np.array([30,12,60,45,90,112])
print("*"*100)
print("Natural log:",np.log(arrayA))
print("Mean from natural log:",np.mean(np.log(arrayA)))
print("*"*100)
print("Log2:",np.log2(arrayA))
print("Mean from log2:",np.mean(np.log2(arrayA)))
print("*"*100)
print("Log10:",np.log10(arrayA))
print("Mean from log10:",np.mean(np.log10(arrayA)))
print("*"*100)
print("Reciprocal Transformation:",1/arrayA)
print("Mean from reciprocal Transformation:",np.mean(1/arrayA)) # Lowest 
print("*"*100)
print("Square root Transformation:",np.sqrt(arrayA))
print("Mean from Square root Transformation:",np.mean(np.sqrt(arrayA)))
print("*"*100)
print("Cube root Transformation:",np.cbrt(arrayA))
print("Mean from Cube root Transformation:",np.mean(np.cbrt(arrayA)))
print("*"*100)

****************************************************************************************************
Natural log: [3.40119738 2.48490665 4.09434456 3.80666249 4.49980967 4.71849887]
Mean from natural log: 3.8342366041779887
****************************************************************************************************
Log2: [4.9068906  3.5849625  5.9068906  5.4918531  6.4918531  6.80735492]
Mean from log2: 5.531634134442524
****************************************************************************************************
Log10: [1.47712125 1.07918125 1.77815125 1.65321251 1.95424251 2.04921802]
Mean from log10: 1.6651877995059634
****************************************************************************************************
Reciprocal Transformation: [0.03333333 0.08333333 0.01666667 0.02222222 0.01111111 0.00892857]
Mean from reciprocal Transformation: 0.029265873015873013
****************************************************************************************************


In [ ]:
Important functions in numpy 

In [ ]:
np.where() 

In [287]:
# Note: To get the index of repeating elements
lst = [1,2,3,2,1,1]
lst.index(2)# 1 scans from left to right 

1

In [288]:
for i,v in enumerate(lst): 
    if v==2: print(i,end=" ")

1 3 

In [289]:
[i for i,v in enumerate(lst) if v==2]

[1, 3]

In [290]:
[i for i,v in np.ndenumerate(lst) if v==2]

[(1,), (3,)]

In [291]:
array = np.array(lst)
np.where(array==2) # Returns index 

(array([1, 3]),)

In [299]:
array = np.array(lst)
np.where((array==2) | (array==3)) # Returns index 

(array([1, 2, 3]),)

In [ ]:
array = np.array(lst)
np.where(array==2,20,np.where(array==3,30,array)) # Returns index 
# Doesnt update 

array([ 1, 20, 30, 20,  1,  1])

In [ ]:
Hence to replace multiple elements with different values we have to write multiple np.where statements

In [ ]:
2] np.argmin()
a] Returns the index of the first minimum value in an array 
b] Return first occurence only 
c] Returns the indices of the minimum values along an axis
2] np.argmax()
a] Returns the index of the first maximum value in an array 
b] Return first occurence only 
c] Returns the indices of the maximum values along an axis

In [312]:
array = np.array(lst)
print(np.argmin(array))
print(array[np.argmin(array)])
print(np.argmax(array))
print(array[np.argmax(array)])

0
1
2
3


In [ ]:
np.delete(array,index)
- Delete specified elements from an array 

In [320]:
array = np.array(lst)
print(array)
array2 = np.delete(array,2) #Doesnt update
print(array)
print(array2)
array3 = np.delete(array,[1,2]) 
print(array3)

[1 2 3 2 1 1]
[1 2 3 2 1 1]
[1 2 2 1 1]
[1 2 1 1]


In [321]:
array1 = np.array([1,2,3,4,5,6])
array2 = np.delete(array1,[0,1])
array2

array([3, 4, 5, 6])

In [ ]:
np.cumsum()
- Cumulative sum of elements along a given axis

In [322]:
array1 = np.array([1,2,3,4,5,6])
print(np.cumsum(array1))

[ 1  3  6 10 15 21]


In [ ]:
np.isnan() - If value is nan return True else return False

In [325]:
array = np.array([2,3,np.nan,4,5,np.nan,6,7])
print(np.isnan(array))
mask = np.isnan(array)
print(array[mask])
print(array[np.isnan(array)])

[False False  True False False  True False False]
[nan nan]
[nan nan]


In [ ]:
np.select(condlist=,choicelist=,default=)

In [ ]:
It allows us to choose value from multiple option based on multiple conditions. 

In [ ]:
prices = np.array([200,40,60,350,625,787,9100,9511,9811])
choices = ['Low Range','Medium Range','High Range']
conditions = [prices<100,(prices>=100) & (prices<1000),prices>=1000]

In [331]:
array = np.select(condlist=conditions,choicelist=choices,default="U")
array

array(['Medium Range', 'Low Range', 'Low Range', 'Medium Range',
       'Medium Range', 'Medium Range', 'High Range', 'High Range',
       'High Range'], dtype='<U12')

In [ ]:
array = np.select(conditions,choices,"U")
array

array(['Medium Range', 'Low Range', 'Low Range', 'Medium Range',
       'Medium Range', 'Medium Range', 'High Range', 'High Range',
       'High Range'], dtype='<U12')

In [ ]:
prices = np.array([200,40,60,350,625,787,9100,9511,9811])
choices = ['Low Range','High Range']
conditions = [prices<100,prices>=1000]

In [333]:
array = np.select(conditions,choices,"Medium Range")
array

array(['Medium Range', 'Low Range', 'Low Range', 'Medium Range',
       'Medium Range', 'Medium Range', 'High Range', 'High Range',
       'High Range'], dtype='<U12')

In [ ]:
1] np.array(list/tuple/dict/Series,ndmin=,dtype="") - To create numpy array 
2] array.ndim() - To know the dimensions of an array 
3] array.shape() - To know the shape of the array
4] array.size() - To know the total number of elements of the array 
5] array.reshape(new_shape) - To change the shape of the array
6] np.nditer(array) - Iterates over an array element wise 
7] np.ndenumerate(array) - Iterates over an array element wise and also return index of that element 
8] array.tolist() - To convert an array into a list
9] array.flatten() - To convert multi-dimensional array into a 1-dimensional array
10] array.copy() - To copy array to other variable 
11] np.zeros(shape,dtype=) - Returns an array of 0 for mentioned shape # default dtype: float  
12] np.ones(shape,dtype=) - Returns an array of 1 for mentioned shape # default dtype: float  
13] np.full(shape,value,dtype=) - Returns an array of value for mentioned shape # default dtype: int  
14] np.append(arr1,arr2,axis=) - Join 2 arrays/Add one array to the existing one #axis=0 (row-wise) #axis=1 (column-wise)
15] np.concatenate([arr1,arr2,arr3,..,arrN],axis=) - Join multiple arrays
16] np.arange(low,high,step_size) 
17] np.random()
np.random.rand(size=) - It generates random floating values between 0 and 1 
np.random.ranf(size=) - It generates random floating values between 0 and 1 
np.random.sample(size=) - It generates random floating values between 0 and 1 
np.random.randint(low=,high=(exclude),size=) - It generates random integers within the specified range 
np.random.uniform(low=,high=(exclude),size=) - It generates random floating values within the specified range 
np.random.randn(shape) - It returns samples of normally distributed data
18] np.around() - Rounds an array to the given number of decimals 
19] np.floor() - Returns the floor of the input,element-wise
20] np.ceil() - Returns the ceil of the input,element-wise
21] np.add() - Add arguments element-wise
22] np.multiply() - Multiply arguments element-wise 
23] np.dot() - Dot product of 2 matrices(Scalar product)
24] np.sqrt() - Returns the non-negative square root of an array, element-wise
25] np.cbrt() - Returns the cube root of an array,element-wise 
26] np.abs() - Returns the positive of an array,element-wise
27] np.max(array,axis=) - Returns the maximum of an array or maximum along axis 
28] np.min(array,axis=) - Returns the minimum of an array or minimum along axis 
29] np.sum(array,axis=) - Compute the sum along the specified axis
30] np.mean(array,axis=) - Compute the arithmetic mean along the specified axis
31] np.median(array,axis=) - Compute the median along the specified axis
32] np.var(array,axis=) - Compute the variance along the specified axis
33] np.std(array,axis=) - Compute the standard deviation along the specified axis
34] np.percentile(array,q,axis=) - Compute the qth percentile along the specified axis
35] np.quantile(array,q,axis=) - Compute the qth quantile along the specified axis
36] np.nanmax(array,axis=)
37] np.nanmin(array,axis=)
38] np.nansum(array,axis=)
39] np.nanmean(array,axis=)
40] np.nanmedian(array,axis=)
41] np.nanvar(array,axis=)
42] np.nanstd(array,axis=)
43] np.nanpercentile(array,axis=)
44] np.nanquantile(array,axis=)
45] scipy.stats.mode
46] np.linalg.solve(arrayA,arrayB)
47] np.linalg.det(square_matrix)
48] np.linalg.inv(square_matrix)
49] np.linalg.matrix_transpose(matrix)
50] np.linalg.eig(array)
51] np.linalg.eigvals(array)
52] eq = np.polynomial.Polynomial(coefficients)
53] eq.roots()
54] np.identity()
55] np.eye()
56] np.deg2rad(degree)
57] np.rad2deg(radian)
58] np.sin(radian)
59] np.cos(radian)
60] np.tan(radian)
61] np.unique(array)
62] np.union1d(array1,array2)
63] np.intersect1d(array1,array2)
64] np.setdiff1d(array1,array2)
65] np.setxor1d(arrat1,arra2)
66] np.put(array,indices,values)
67] np.repeat(value,n)
68] np.sort(array)
69] np.where()
70] np.argmax(array)
71] np.argmin(array)
72] np.delete(array,indices)
73] np.cumsum(array,axis=)
74] np.isnan(array)
75] np.select(condlist=,choicelist=,default=)
76] np.log(array)
77] np.log2(array)
78] np.log10(array)
